# Generated by Django 3.0.6 on 2020-05-24 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 24, 4, 34, 53, 577223)),
        ),
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=500),
        ),
    ]
