# Generated by Django 3.0.7 on 2020-06-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200608_1534'),
        ('home', '0005_auto_20200526_0748'),
    ]

    operations = [
    ]
